# Generated by Django 5.0.6 on 2024-06-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0002_chatgroup_owner'),
    ]

    operations = [
        migrations.RunSQL('''
            INSERT INTO a_chat_chatgroup (id, group_name)
                VALUES (1, 'public-chat')
        ''')
    ]