# Generated by Django 5.0.6 on 2024-06-19 00:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_chat', '0003_insert_public_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GruopMessage',
            new_name='GroupMessage',
        ),
    ]
